version: '0.19'

services:
  db:
    image: postgres:16.1
    container_name: veterinaria
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nico0603
      POSTGRES_DB: Veterinaria_db
    ports:
      - "5454:5432"
    networks:
      - Veterinaria-net
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: veterin_psql
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_HOST= db
      - DATABASE_PORT= 5454
      - DATABASE_NAME= veterinaria_db
      - DATABASE_USER= postgres
      - DATABASE_PASSWORD= Nico0603
    networks:
      - Veterinaria-net
    volumes:
      - "C:/Users/Nico/Documentos/VeterinariaProyecto:/app"


volumes:
  db_data:

networks:
  Veterinaria-net: