version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: veterinaria_db
    environment:
      POSTGRES_USER: tuusuario
      POSTGRES_PASSWORD: Nico0603
      POSTGRES_DB: Veterinaria_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: