version: '16.1'

services:
  db:
    image: postgres:16.1
    container_name: veterinaria
    environment:
      POSTGRES_USER: Nicolas
      POSTGRES_PASSWORD: Nico0603
      POSTGRES_DB: Veterinaria_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: